In [1]:
import tensorflow as tf
print(tf.__version__)

2.13.0


# 1. 텐서플로
### 텐서플로에서 텐서 만들기

In [4]:

import numpy as np

a = np.array([1, 2, 3], dtype=np.int32)
b = [4, 5, 6]

t_a = tf.convert_to_tensor(a) #tf.convert_to_tensor : 리스트나 넘파이 배열에서 텐서 만들기
t_b = tf.convert_to_tensor(b)

print(t_a)
print(t_b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 6], shape=(3,), dtype=int32)


In [5]:
t_ones = tf.ones((2, 3)) #tf.ones : 2x3 행렬 만들기

t_ones.shape #행렬의 모양 출력 -> TensorShape([2, 3])

TensorShape([2, 3])

In [6]:
t_ones.numpy() #참조값 얻기 -> array([[1., 1., 1.], [1., 1., 1.]], dtype=float32)

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [8]:
const_tensor = tf.constant([1.2, 5, np.pi], dtype=tf.float32)  #tf.constant : 상수 텐서

print(const_tensor)

tf.Tensor([1.2       5.        3.1415927], shape=(3,), dtype=float32)


In [9]:
t_a_new = tf.cast(t_a, tf.int64) #tf.cast : 데이터 타입 바꾸기

print(t_a_new.dtype)

<dtype: 'int64'>


In [11]:
t = tf.random.uniform(shape=(3, 5)) 

t_tr = tf.transpose(t)#tf.transpose: 전치
print(t.shape, ' --> ', t_tr.shape)

(3, 5)  -->  (5, 3)


In [12]:
t = tf.zeros((30,))

t_reshape = tf.reshape(t, shape=(5, 6)) #tf.resagoe ;: 크기 바꾸기

print(t_reshape.shape)

(5, 6)


In [13]:
t = tf.zeros((1, 2, 1, 4, 1))

t_sqz = tf.squeeze(t, axis=(2, 4)) #tf.squeeze : 불필요한 차원 (크기가 1인 차원)은 삭제

print(t.shape, ' --> ', t_sqz.shape)

(1, 2, 1, 4, 1)  -->  (1, 2, 4)


### 텐서에 수학 연산 적용

In [ ]:
tf.random.set_seed(1)

t1 = tf.random.uniform(shape=(5, 2),
                       minval=-1.0,
                       maxval=1.0)

t2 = tf.random.normal(shape=(5, 2),
                      mean=0.0,
                      stddev=1.0)